version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "9000:9000"
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: Dockerfile.DB
    image: postgres
    environment:
      POSTGRES_DB: Feedback
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Zopa_kek12
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      -./DB:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
