version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html/

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "9000:9000"
    depends_on:
      - database_service

  database_service:
    build:
      context: .
      dockerfile: Dockerfile.database_service
    ports:
      - "9001:9001"
    depends_on:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_DB: Feedback
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Zopa_kek12
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
